### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by TheHeroBilly** [Eslyium/Eslyium-Cogs#3]
I was wondering before I install a cog of yours (NSFW) if I can restrict it to a specified chat and how would I do it, if it was available?

**Comment by Eslyium** [comment]
Eh.. I didn't include that feature just due to Squids permission cog which can basically do everything you want it to permission wise for users. Ill think about it though

**Comment by TheHeroBilly** [comment]
Can you give me a link to the cog repo?

**Comment by Eslyium** [comment]
https://github.com/tekulvw/Squid-Plugins
